### ISSUE TITLE
Demo is not working after removing bootstrap JS which is not defined in the documentation, Kindly assist,  

### ISSUE THREAD

**Issue by gulariav** [sebnitu/Quovolver#16]
I have just downloaded the demo (master zip) but didn't find the next/prev button controls. Also when removed Bootstrap js everything is gone. Kindly assist how we can navigation without bootstrap js.

Thanks

**Comment by sebnitu** [comment]
There are next/prev options (documented in the demo) that are set to false by default.

**Comment by gulariav** [comment]
I mean to say i have enable them (set to true) but they are not visible. is there any trick to show them?? Kindly assist, Thanks
